### ISSUE TITLE
Cant create train datasets

### ISSUE THREAD

**Issue by vdeng-ai** [val-iisc/crowd-counting-scnn#1]
Hi there,
I was trying to train SCNN, but cannot find create_density() when running create_datasets.m. 
And cannot find MCNN code on the Internet either.
Could you tell me how to find MCNN code?
Thank you very much!

**Comment by weizheliu** [comment]
The same case for me, please point out where we could find this script, ideally the MCNN code. Thanks a lot.

**Comment by pankajbadatia** [comment]
replace create_density with create_dotmaps

**Comment by shivsurya** [comment]
Readme updated to answer your question

**Comment by asif07hossain** [comment]
I am Asiful, grad student from University of Manitoba, canada. Currently, I am doing research on crowd counting. Regarding this I am in great need of UCSD data pre processing code. Will you please help me out by sending the pre processing code.
email: asif07hossain@gmail.com
