### ISSUE TITLE
Error with matfiles while running test_scnn

### ISSUE THREAD

**Issue by MounirB** [val-iisc/crowd-counting-scnn#15]
Hello,

When I run test_scnn.py, I encounter the following error

> Traceback (most recent call last):
>   File "/home/mounir/PycharmProjects/crowd-counting-scnn-master/src/test_scnn.py", line 132, in <module>
>     _, _, txt = test_scnn(test_funcs, datasets['test'])
>   File "/home/mounir/PycharmProjects/crowd-counting-scnn-master/src/test_scnn.py", line 35, in test_scnn
>     for i, (X, Y) in enumerate(dataset):
>   File "/home/mounir/PycharmProjects/crowd-counting-scnn-master/src/data_reader.py", line 62, in __iter__
>     os.path.splitext(f)[0] + '.mat'))
>   File "/home/mounir/miniconda3/envs/R21Dcaffe2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
>     MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
>   File "/home/mounir/miniconda3/envs/R21Dcaffe2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 65, in mat_reader_factory
>     mjv, mnv = get_matfile_version(byte_stream)
>   File "/home/mounir/miniconda3/envs/R21Dcaffe2/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
>     raise ValueError('Unknown mat file type, version %s, %s' % ret)
> ValueError: Unknown mat file type, version 120, 10

It seems to be provoked by .mat files. Any guess on what should I do to solve it ?

**Comment by norahik** [comment]
what version of matlab you are using? did you try to load one mat file individually providing full path to see if is opens? try creating new mat file from matlab and open it. if the new file opens it could be the mat files you have are not compatible with matlab version you have.

**Comment by MounirB** [comment]
Instead of Matlab, I use Octave
