### ISSUE TITLE
snapshot folder is not created

### ISSUE THREAD

**Issue by norahik** [val-iisc/crowd-counting-scnn#18]
while running differential training i got the following error:

Traceback (most recent call last):
  File "/Users/norah/crowd-counting-scnn/src/differential_train.py", line 141, in <module>
    train()
  File "/Users/norah/crowd-counting-scnn/src/differential_train.py", line 134, in train
    train_differential(networks, datasets, train_funcs, test_funcs, path)
  File "/Users/norah/crowd-counting-scnn/src/differential_train.py", line 65, in train_differential
    save_nets(diff_trained_model_files, networks[1: ])
  File "/Users/norah/crowd-counting-scnn/src/utils.py", line 34, in save_nets
    fp = open(file_name, 'wb')
IOError: [Errno 2] No such file or directory: './models/differential_train/snapshots/shallow_9x9_0.pkl'

it i looked for folder snapshot and its not created.
any idea why?

**Comment by mtakhsha94** [comment]
I created this folder in differential training folder and it worked.

**Comment by norahik** [comment]
it worked, thank you
i created snapshot folder under differential_train and coupled_train and added a copy of .pkl files into them.

but i'd like an explanation on what was wrong and why that worked.

**Comment by mtakhsha94** [comment]
@norahik you're welcome
Actually, this is a folder for the models that the program produce within a learning, so you don't need to copy .pkl files in the snapshot folder
I'm not very good at python, I think the python couldn't create the folder like what Matlab does when you don't make the folder by yourself, so it needs to make a folder.
or maybe it doesn't code to create this folder in the scnn code
I hope my explanations help you :)
