### ISSUE TITLE
What kind of data you use while testing?

### ISSUE THREAD

**Issue by ddstone** [val-iisc/crowd-counting-scnn#2]
Which dataset do you use in path './ST_part_A/', is it ShanghaiTech_Crowd_Counting_Dataset? Best Regards.

**Comment by OliverUrbann** [comment]
Where can I get this dataset? Google does not help searching ShanghaiTech_Crowd_Counting_Dataset and anything similar.

**Comment by AaronHu13** [comment]
https://github.com/desenzhou/ShanghaiTechDataset

Here is the link
