### ISSUE TITLE
Testing in realtime video

### ISSUE THREAD

**Issue by Zumbalamambo** [val-iisc/crowd-counting-scnn#3]
how do I test in realtime video?

**Comment by shivsurya** [comment]
Use a video reader object in your language of choice. As an example, in Matlab you could use [this ](https://in.mathworks.com/help/matlab/ref/videoreader.html?requestedDomain=www.mathworks.com) to dump frames. These frames are essentially single images and can be processed by the model. I would suggest temporal subsample to reduce the compute for a high FPS video. Our model does not incorporate temporal information explicitly. You can try architectural modifications but they are out of scope for discussion here.
