### ISSUE TITLE
problem when testing...

### ISSUE THREAD

**Issue by fgxfxpfzzfcc** [val-iisc/crowd-counting-scnn#4]
TEST dataset sorting files...
Done
Traceback (most recent call last):
  File "/home/dl/file/fcc/crowd-counting-scnn-master/src/test_scnn.py", line 122, in <module>
    deep_patch_classifier(),
  File "/home/dl/file/fcc/crowd-counting-scnn-master/src/networks.py", line 121, in __init__
    W = lasagne.init.Normal(std=0.01, mean=0.0))
  File "/home/dl/anaconda2/lib/python2.7/site-packages/lasagne/layers/conv.py", line 391, in __init__
    super(Conv2DLayer, self).__init__(incoming, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'flip_filters'

I meet the problem TypeError: __init__() got an unexpected keyword argument 'flip_filters'.

**Comment by AaronHu13** [comment]
I got this problem,too. I figured out by update Theano (It would bring lots of other problems)

**Comment by shivsurya** [comment]
This is a version mismatch. Will revert with versions when I find time

**Comment by so-as** [comment]
@fgxfxpfzzfcc @Aaron0813 @shivsurya @BardOfCodes @altairmn Hi, I got the same problem. What is the right solution for solve this. Wait for your reply, thank you!

**Comment by YoungerGao** [comment]
@shivsurya Hi, I got the same problem, maybe the right version of theano and lasagne will fix this problem , can you tell me your version used for compile？
By the way, I could run after I deleted the flip_filters, is the result right?

**Comment by tzcqu** [comment]
how long to train partA and test partA, it seems too long in my exp.

**Comment by ninghongbo123** [comment]
pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
THIS WILL WORK  WELL!
