### ISSUE TITLE
create_density.m missing

### ISSUE THREAD

**Issue by Viresh-R** [val-iisc/crowd-counting-scnn#5]
Hey, could you please add the missing file create_density.m ?

Thanks !!

**Comment by pankajbadatia** [comment]
The author is not interested I think so in giving code. only half code is given . And doesn't even respond to emails. Please think twice before downloading this code. Half code is not worth of use to anyone .

**Comment by pankajbadatia** [comment]
replace create_density with create_dotmaps in the code

**Comment by pankajbadatia** [comment]
Rename ground-truth with ground_truth .... please see there is difference between hyphen and underscore

**Comment by shivsurya** [comment]
Readme updated to answer your question
