### ISSUE TITLE
Problem about testing result

### ISSUE THREAD

**Issue by ShirleyGxd** [val-iisc/crowd-counting-scnn#9]
I test the code on the 'test_data' of ShanghaiTech crowd counting dataset and used the given 'coupled_train' model. But I got a result which is different from the paper. The MAE_image result is 58.79 in Part B, bigger than 21.6 which is shown in the paper,  and  88.355 in Part A which is similar to the result in paper.
The test was done on Windows10. Is that the reason why I got the different reult? Or for Part B, I need to do additional data process/network tuning?

The follwing is the result of **Part B's test data**:
![original](https://user-images.githubusercontent.com/31054207/37519781-6606ead6-2955-11e8-995a-4a1082fd3fc0.PNG)

The follwing is the result of **Part A's test data**:
![dataa_scnn_gpu2](https://user-images.githubusercontent.com/31054207/37520142-df2f86e2-2956-11e8-9b98-ac4be3079112.PNG)

**Comment by XcodeHw** [comment]
I got a result which is different from the paper,We have almost the same result,finally how to solve this problem？
